### ISSUE TITLE
Is there a modern version?

### ISSUE THREAD

**Issue by almaruf** [hasinhayder/bnKbjQuery#1]
I am having this issue on my old site with 
jquery-2.2.4
Cannot set property 'chrome' of undefined -  engine.js:30

**Comment by mayeenulislam** [comment]
@almaruf In one of our system, if I recall correctly, we faced similar problem. Then we used [jquery-browser-plugin](https://github.com/gabceb/jquery-browser-plugin/releases).

The stack was like below:
```
'jquery.browser.min.js', // <--------- this one here
'engine.js',
'driver.phonetic.js',
'driver.probhat.js',
'driver.unijoy.js', // forgot where we got the modified one, but you can have one**
'switch-bengali-keyboard.js', // our own code to trigger the switches
```

** [Deprecated Unijoy layout this repo](https://raw.githubusercontent.com/hasinhayder/bnKbjQuery/ad8fb5c347e174edcc4ec970f51a0278aa509c7b/driver.unijoy.js)

**Comment by almaruf** [comment]
@mayeenulislam  - oh yes, that was the problem :) but the doc should mention this.
